# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifestss
    target-branch: 'main'
    schedule:
      interval: 'daily'
    registries:
      - Artifactory


registries:
  Artifactory:
    type: npm-registry
    url: https://hts2.jfrog.io/artifactory/ca-npm-test
    username: frogtester3
    #password: ${{secrets.MY_ARTIFACTORY_PASSWORD}}
    #token: ${{secrets.JFROG_ACCESS_TOKEN}}
    password: ${{secrets.MY_ARTIFACTORY_PASSWORD}}
    #username: xxx
    replaces-base: true
    #password: ${{secrets.MY_ARTIFACTORY_PASSWORD}}
