# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest
- task: ArtifactoryGenericDownload@3
  inputs:
    connection: 'hts-latest'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "/Users/bandih/.jfrog/plugins/plugins.yml"
          }
        ]
      }
    failNoOp: true
    minSplit: '50000'