# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArtifactoryGenericDownload@3
  inputs:
    connection: 'hts-latest'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "generic-fame-obs-prod-local/windows_exporter/windows_exporter-0.20.0-amd64.exe"
          }
        ]
      }
    failNoOp: true
    minSplit: '50000'